name: liropa
favicon: null
layout_spectrum: 0.48945
typography_spectrum: 0.41480287443846464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70241768-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.16346871689893305
  lightness: 0.17974985763430595
  saturation: 0.6844068875070661
  rhythmicContrast: 0.009056919487193227
purpose: []
